Part1
michaelmon1203/PFMCPP_Project3 pull request #1
Opened 2022-07-18 06:46 UTC by michaelmon1203

Finally got my homework onto Github through Replit!

2022-07-18 18:01 UTC, matkatmusic requested changes

2022-07-18 18:01 UTC, matkatmusic commented on main.cpp
> +Thing 2) Do YouTube
Do Youtube is an activity (action).  
it is not a noun.
- [ ] pick a noun

2022-07-18 18:01 UTC, matkatmusic commented on main.cpp
> +Thing 3) Song Writing
Song Writing is an activity (action).  
it is not a noun.
- [ ] pick a noun

2022-07-18 18:01 UTC, matkatmusic commented on main.cpp
> +Thing 4) Product Management
This is not an ideal object.  
it is too abstract. 
Your properties and actions are describing a **Product Manager.**  
- [ ] change the Thing

2022-07-19 05:43 UTC, matkatmusic requested changes
I have added the next set of instructions. 
CODE THEM UP!!

2022-07-21 03:59 UTC, matkatmusic requested changes

2022-07-21 03:59 UTC, matkatmusic commented on main.cpp
> +    int numberOfPeopleWhoListened = 5000;
You are missing a property.
and all of your properties are `int`
- [ ] revise

2022-07-21 03:59 UTC, matkatmusic commented on main.cpp
> +};
Add a nested type to this UDT
`TourManager` is a good choice
- [ ] revise

2022-07-21 03:59 UTC, matkatmusic commented on main.cpp
> +    void reachToTheAudience(int platformAmount, YouTuber recordLabelA);
YouTubers aren't record labels.  They're content creators.
Pick a variable name that makes sense.
- [ ] revise

2022-07-21 03:59 UTC, matkatmusic commented on main.cpp
> +        bool sixthStringWound = true;
These are not properties relevant to a string type. 
These are properties of a guitar. 
I would remove this nested class entirely, and choose a different UDT to add a nested class to.
- [x] revise

2022-07-21 03:59 UTC, matkatmusic commented on main.cpp
> +
Delete all of this.
You already declared these classes earlier in the source file. 
you declare instances of THOSE classes.  
You don't copy those class definitions into this class.
- [ ] revise

2022-07-21 04:37 UTC, michaelmon1203 commented on main.cpp
> +        bool sixthStringWound = true;
Ok, I deleted these and added nested class BandManager in RockBand.

2022-07-21 05:02 UTC, matkatmusic approved these changes

2022-07-21 05:02 UTC, merged